# Midpoint [x,y,z,...] for circle arc
float64[] mid
# Endpoint [x,y,z,...] for circle arc
float64[] end
int32 rel 0
float64 vel 0.0
float64 accel 0.0
float64 jerk 0.0
int32 cont 0
float64 corner 50.0
float64 timeout -1.0
---
bool success
string message
